steps:

  # Step 1: Check out the repository using GITHUB_TOKEN
  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    secretEnv:
      - GITHUB_TOKEN
    args:
      - "-c"
      - |
        echo "Cloning from GitHub with authentication..."
        git clone https://$$GITHUB_TOKEN@github.com/inderanz/gcp-terraform-module.git .
        git remote update
        git fetch
        git checkout origin/main

steps:
  # Step 2: Generate Release PR and Install release-please
  - name: "node:16"
    entrypoint: "bash"
    secretEnv:
      - GITHUB_TOKEN
    args:
      - "-c"
      - |
        echo "Installing release-please in Step 4..."
        npm install -g release-please  # Install release-please in Step 4
        echo "Generating Release PR..."
        release-please github-release-pr \
          --token=$$GITHUB_TOKEN \
          --repo-url=https://github.com/inderanz/gcp-terraform-module \
          --package-name=gcp-terraform-module \
          --default-branch=main


availableSecrets:
  secretManager:
    - versionName: "projects/354449891279/secrets/github-token/versions/latest"
      env: "GITHUB_TOKEN"

timeout: "1200s"

options:
  logging: CLOUD_LOGGING_ONLY
