steps:
  # Step 1: Debug Step - Confirm GITHUB_TOKEN is set and used
  - name: "ubuntu"
    entrypoint: "bash"
    secretEnv:
      - GITHUB_TOKEN
    args:
      - "-c"
      - |
        echo "Testing GITHUB_TOKEN..."
        if [ -z "$$GITHUB_TOKEN" ]; then
          echo "ERROR: GITHUB_TOKEN is not set!"
          exit 1
        else
          echo "SUCCESS: GITHUB_TOKEN is available!"
        fi

  # Step 2: Check out the repository using GITHUB_TOKEN
  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    secretEnv:
      - GITHUB_TOKEN
    args:
      - "-c"
      - |
        echo "Cloning from GitHub with authentication..."
        git clone https://$$GITHUB_TOKEN@github.com/inderanz/gcp-terraform-module.git .
        git checkout $BRANCH_NAME

  # Step 3: Install Node.js and release-please
  - name: "node:16"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Installing release-please..."
        npm install -g release-please

  # Step 4: Generate Release PR
  - name: "node:16"
    entrypoint: "bash"
    secretEnv:
      - GITHUB_TOKEN
    args:
      - "-c"
      - |
        echo "Generating Release PR..."
        release-please github-release-pr \
          --repo-url=$REPO_URL \
          --package-name=gcp-terraform-module \
          --default-branch=$BRANCH_NAME \
          --token=$$GITHUB_TOKEN

  # Step 5: Optional - Create GitHub Release
  - name: "node:16"
    entrypoint: "bash"
    secretEnv:
      - GITHUB_TOKEN
    args:
      - "-c"
      - |
        echo "Publishing Release..."
        release-please github-release \
          --repo-url=$REPO_URL \
          --token=$$GITHUB_TOKEN

availableSecrets:
  secretManager:
    - versionName: "projects/354449891279/secrets/github-token/versions/latest"
      env: "GITHUB_TOKEN"

substitutions:
  _REPO_NAME: "gcp-terraform-module"  # Replace with your repository name
  _BRANCH_NAME: "main"               # Replace with your default branch
  _REPO_URL: "https://github.com/inderanz/gcp-terraform-module.git"

timeout: "1200s"
